### ISSUE TITLE
Portfolio - page - scrollbar in modal box

### ISSUE THREAD

**Issue by simogeo** [getgrav/grav-skeleton-deliver-site#8]
Hi, 
Thanks for this delicious deliver-site template. Great work ! 
I'd like to know if there is an easy way to add scrollabr to modal-box in portfolio page ?

I played a bit with css `overflow:auto` property with no success. Thanks for your reply.

**Comment by hexplor** [comment]
Hey, 
Open css-compiled/template.css and add

``` css
.modal .modal-body {
    max-height: 420px;
    overflow-y: auto;
}
```

If you want to make it permanent, add it to scss file and recompile. Good luck :)
